[project]
name = "micrograd"
version = "0.1.0"
description = "A tiny Autograd engine"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.20.3",
    "jupyter>=1.1.1",
    "matplotlib>=3.9.2",
    "numpy>=2.1.3",
    "scikit-learn>=1.5.2",
]
